### ISSUE TITLE
gulp-scp2 crashes when a file is renamed in a watched folder

### ISSUE THREAD

**Issue by playeren** [popomore/gulp-scp2#6]
I honestly don't know if this is due to gulp-scp2, client.js or gulp-watch or my crappy gulpfile.js. But the following always happens when I rename a file in a watched folder. Win 8.1, Node v6.9.2, gulp + gulp-cli v3.9.1

```
\node_modules\scp2\lib\client.js:220
        throw new Error('Content should be buffer or file descriptor');
        ^

Error: Content should be buffer or file descriptor
    at _write (\frejalocal\node_modules\scp2\lib\client.js:220:15)
    at \frejalocal\node_modules\scp2\lib\client.js:238:9
    at SFTP._parse (\frejalocal\node_modules\ssh2\lib\SFTP\SFTPv3.js:1110:11)
    at ChannelStream.<anonymous> (\frejalocal\node_modules\ssh2\lib\SFTP\SFTPv3.js:72:10)
    at emitOne (events.js:96:13)
    at ChannelStream.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at ChannelStream.Readable.push (_stream_readable.js:134:10)
    at Parser.<anonymous> (\frejalocal\node_modules\ssh2\lib\Channel.js:102:25)
    at emitOne (events.js:96:13)
```
The task where scp2 is used:

```
gulp.task('tripFreja', function() {
    watch(source0)
        .pipe(plumber())
        .on('error', function(err) {
            handleError(err);
            logga(timeDate() + ' ' + err);
        })
        .pipe(print(function(filepath) {
            return 'staging: ' + filepath;
        }))
        .pipe(replace(/(freshbuild:)(?!\))\'?\s?(.+(?=\')|.+(?=\})|\w+)/g, function(match, p1, p2) {
            return p1 + '\'' + date() + '-' + time() + ' devmsg: ' + p2 + '\'';
        }, { skipBinary: true }))
        .on('error', function(err) {
            handleError(err);
            logga(timeDate() + err);
        })
        .pipe(gulp.dest(commitDir + 'FREJA/'))
        .pipe(scp({
            host: '0.0.0.0',
            port: 22,
            username: secret.un,
            password: secret.pw,
            dest: '/srv/'
        }))
        .on('end', function() {
            logga(timeDate() + 'files sent to FrejaDev: ' + fileName);
        })
        .on('error', function(err) {
            //console.log(err);
            handleError(err);
            logga(timeDate() + ' scp err: ' + err);
        });
});

**Comment by popomore** [comment]
Can you add a data event after gulp.dest to see is every file object exist?
And why do you scp after write to dest
John MHM {freshnode} <notifications@github.com>于2016年12月21日 周三01:28写道：

**Comment by playeren** [comment]
Thanks for the hint. I now filter on event !== 'unlink' which were the types that broke things. 

I first write the changed files to dest in a folder named like this: `'../commits/' + date() + '_' + time() + '/'`, so it's kind of a homerolled version control, making it easy to do partial or full rollbacks. Then it uses scp to send them to a local test+staging srv.
