### ISSUE TITLE
TypeError: Path must be a string. Received undefined

### ISSUE THREAD

**Issue by axelrindle** [popomore/gulp-scp2#7]
I got the following setup (CoffeeScript):

```coffeescript
# require modules from npm
gulp = require 'gulp'
scp = require 'gulp-scp2'
prompt = require('prompt-sync')()

# paths config
paths = require '../paths.json'

# set up ssh
sshConf =
  host: 'axel-pi'
  username: 'git'
  password: prompt.hide 'Enter the password to copy the files: '
  dest: paths.dist.output # /var/www

# copy files to www folder on the raspberry pi
task = ->
  gulp.src paths.dist.input # array with files
    .pipe scp sshConf

# register the task
gulp.task 'dist', task
```

When trying to run the task, it results in the following error:

```
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:799:5)
    at C:\Users\Axel Rindle\Projekte\adamgit\node_modules\scp2\lib\client.js:228:29
    at SFTP._parse (C:\Users\Axel Rindle\Projekte\adamgit\node_modules\ssh2\lib\SFTP\SFTPv3.js:1093:13)
    at ChannelStream.<anonymous> (C:\Users\Axel Rindle\Projekte\adamgit\node_modules\ssh2\lib\SFTP\SFTPv3.js:72:10)
    at emitOne (events.js:96:13)
    at ChannelStream.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at ChannelStream.Readable.push (_stream_readable.js:136:10)
    at Parser.<anonymous> (C:\Users\Axel Rindle\Projekte\adamgit\node_modules\ssh2\lib\Channel.js:102:25)
    at emitOne (events.js:96:13)
    at Parser.emit (events.js:191:7)
    at Parser.parsePacket (C:\Users\Axel Rindle\Projekte\adamgit\node_modules\ssh2\lib\Parser.js:607:12)
    at Parser.execute (C:\Users\Axel Rindle\Projekte\adamgit\node_modules\ssh2\lib\Parser.js:249:14)
    at Socket.<anonymous> (C:\Users\Axel Rindle\Projekte\adamgit\node_modules\ssh2\lib\Connection.js:536:18)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at readableAddChunk (_stream_readable.js:178:18)
    at Socket.Readable.push (_stream_readable.js:136:10)
    at TCP.onread (net.js:561:20)
```

I don't know what's going on.

I can imagine this is an issue with [scp2](https://github.com/spmjs/node-scp2) itself, but I'm posting this here as your plugin builds upon **scp2**.

**Comment by ffdead** [comment]
@axelrindle did you ever figure this out? Got the same issue

**Comment by axelrindle** [comment]
@ffdead Unfortunately not, ended up doing it with a bash script.

**Comment by ffdead** [comment]
Too bad, thanks!
